# This is a basic workflow to help you get started with Actions

name: deploy to server

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
   branches: [ "main" ]
  pull_request:
   branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v4

      - name: install dep
        run: |
          sudo apt update
          sudo apt install nodejs
          npm install

      - name: build website file
        run: npm run generate

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          scp_source: ./output/public/
          scp_target: /opt/1panel/apps/openresty/openresty/www/sites/www.craft233.top/index/
